=== DirectProject/nhin-d/csharp/tools/trust.bundler/bundle/TrustBundleMetadata.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="TrustBundle">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Profile" minOccurs="1" maxOccurs="1"/>
        <xs:element ref="DistributionPoint" minOccurs="1" maxOccurs="unbounded"/>
        <xs:element ref="ValidFrom" minOccurs="0" maxOccurs="1"/>
        <xs:element ref="ValidTo" minOccurs="0" maxOccurs="1"/>
        <xs:element ref="Anchors" minOccurs="0" maxOccurs="1"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Profile" type="xs:string"/>
  <xs:element name="Anchors">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Anchor" minOccurs="1" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Anchor">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="X509IssuerSerial" minOccurs="1" maxOccurs="1"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="X509IssuerSerial">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="X509IssuerName" minOccurs="1" maxOccurs="1"/>
        <xs:element ref="X509SerialNumber" minOccurs="1" maxOccurs="1"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="X509IssuerName" type="xs:string"/>
  <xs:element name="X509SerialNumber" type="xs:integer"/>
  <xs:element name="ValidFrom" type="xs:dateTime"/>
  <xs:element name="ValidTo" type="xs:dateTime"/>
  <xs:element name="DistributionPoint" type="xs:anyURI"/>
</xs:schema>

=== DirectProject/nhin-d/java/trust-bundle/src/test/resources/testdatainput/TrustBundleMetadata.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!-- MetaData File For LoA 3 TrustBundle -->
<TrustBundle xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="TrustBundleMetaData.xsd">
    <Profile>DirectTrust LoA-3</Profile>
    <DistributionPoint>http://www.trust.org/trustbundle1.p7b</DistributionPoint>
    <ValidFrom>2013-02-12T00:00:00</ValidFrom>
    <ValidTo>2014-02-12T00:00:00</ValidTo>
    <Anchors>
        <Anchor>
            <X509IssuerSerial>
                <X509IssuerName>CN=Direct L3 CA, OU=Issued By DigiCert, O=HISP Name, L=Town, ST=UT, C=US</X509IssuerName>
                <X509SerialNumber>12345678</X509SerialNumber>
            </X509IssuerSerial>
        </Anchor>
    </Anchors>
</TrustBundle>
